//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Mems = new HashSet<Mem>();
            this.joblistns = new HashSet<joblistn>();
        }
    
        public short COUNTRYID { get; set; }
        public string countryname { get; set; }
    
        public virtual ICollection<Mem> Mems { get; set; }
        public virtual ICollection<joblistn> joblistns { get; set; }
    }
}
