//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumMainCategory
    {
        public ForumMainCategory()
        {
            this.ForumSubCategories = new HashSet<ForumSubCategory>();
            this.ForumTopics = new HashSet<ForumTopic>();
        }
    
        public long catid { get; set; }
        public string Category { get; set; }
        public string descrip { get; set; }
        public System.DateTime StartDate { get; set; }
        public long memsid { get; set; }
    
        public virtual Mem Mem { get; set; }
        public virtual ICollection<ForumSubCategory> ForumSubCategories { get; set; }
        public virtual ICollection<ForumTopic> ForumTopics { get; set; }
    }
}
