//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumTopicAnswer
    {
        public long AnsId { get; set; }
        public long TopicId { get; set; }
        public string TopicAns { get; set; }
        public System.DateTime AnsDate { get; set; }
        public string IsApproved { get; set; }
        public long memsid { get; set; }
    
        public virtual ForumTopic ForumTopic { get; set; }
        public virtual Mem Mem { get; set; }
    }
}
