//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobcategory
    {
        public jobcategory()
        {
            this.joblistns = new HashSet<joblistn>();
            this.Mems = new HashSet<Mem>();
        }
    
        public short jobcategoryid { get; set; }
        public string category { get; set; }
    
        public virtual ICollection<joblistn> joblistns { get; set; }
        public virtual ICollection<Mem> Mems { get; set; }
    }
}
