//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mem
    {
        public Mem()
        {
            this.Photos = new HashSet<Photo>();
            this.joblistns = new HashSet<joblistn>();
            this.ForumMainCategories = new HashSet<ForumMainCategory>();
            this.ForumSubCategories = new HashSet<ForumSubCategory>();
            this.ForumTopics = new HashSet<ForumTopic>();
            this.ForumTopicAnswers = new HashSet<ForumTopicAnswer>();
            this.tbl_Jokes = new HashSet<tbl_Jokes>();
            this.tbl_Jokes1 = new HashSet<tbl_Jokes>();
            this.tbl_Jokes2 = new HashSet<tbl_Jokes>();
        }
    
        public long memsid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string passw { get; set; }
        public long photoid { get; set; }
        public short countryid { get; set; }
        public short stateid { get; set; }
        public short cityid { get; set; }
        public string gurl { get; set; }
        public string gimg { get; set; }
        public string aboutme { get; set; }
        public string susp { get; set; }
        public System.DateTime regDate { get; set; }
        public string isJobseeker { get; set; }
        public string designation { get; set; }
        public Nullable<short> jobcategoryid { get; set; }
        public string sponsoremail { get; set; }
    
        public virtual citytable citytable { get; set; }
        public virtual Country Country { get; set; }
        public virtual state state { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual ICollection<joblistn> joblistns { get; set; }
        public virtual ICollection<ForumMainCategory> ForumMainCategories { get; set; }
        public virtual ICollection<ForumSubCategory> ForumSubCategories { get; set; }
        public virtual ICollection<ForumTopic> ForumTopics { get; set; }
        public virtual ICollection<ForumTopicAnswer> ForumTopicAnswers { get; set; }
        public virtual ICollection<tbl_Jokes> tbl_Jokes { get; set; }
        public virtual ICollection<tbl_Jokes> tbl_Jokes1 { get; set; }
        public virtual ICollection<tbl_Jokes> tbl_Jokes2 { get; set; }
        public virtual jobcategory jobcategory { get; set; }
    }
}
