//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meminvite
    {
        public long inviteid { get; set; }
        public long memsid { get; set; }
        public string useremail { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
    }
}
