//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public string photoname { get; set; }
        public string passw { get; set; }
        public System.DateTime uploaddate { get; set; }
        public string mainphoto { get; set; }
        public string isapproved { get; set; }
        public long memsid { get; set; }
        public long photoid { get; set; }
    
        public virtual Mem Mem { get; set; }
    }
}
