//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Jokes
    {
        public long Jokesid { get; set; }
        public long memsid { get; set; }
        public System.DateTime Jokesdate { get; set; }
        public string Jokessub { get; set; }
        public string JokesDesc { get; set; }
        public string Jokespic { get; set; }
        public string ipaddress { get; set; }
        public string IsApproved { get; set; }
        public int categoryId { get; set; }
        public int TotalView { get; set; }
    
        public virtual Jokescatmaster Jokescatmaster { get; set; }
        public virtual Jokescatmaster Jokescatmaster1 { get; set; }
        public virtual Mem Mem { get; set; }
        public virtual Mem Mem1 { get; set; }
        public virtual Mem Mem2 { get; set; }
    }
}
