//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Complaints_Comments
    {
        public long CommentsID { get; set; }
        public long ComplaintsID { get; set; }
        public string Comments { get; set; }
        public long CommentsBy { get; set; }
        public string CommentsByName { get; set; }
        public string IsAdmin { get; set; }
        public System.DateTime CommentsDate { get; set; }
    }
}
